### ISSUE TITLE
Latest version of node-xmpp-client brakes harmonyHubCLI

### ISSUE THREAD

**Issue by sushilks** [sushilks/harmonyHubCLI#1]
Starting hub Discovery
Hub Found at :192.168.0.19
Connecting to hub at 192.168.0.19
Hub Found at :192.168.0.35
Hub Found at :192.168.0.46
/home/pi/harmonyHubCLI/node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/lib/login/hub.js:63
if(response.identity && response.identity !== undefined) {
^
TypeError: Cannot read property 'identity' of undefined

**Comment by sushilks** [comment]
Temporary Fix (Till upstream packages are resolved)

> sed -i.bak 's/"node-xmpp-client".*/"node-xmpp-client":"1.0.0-alpha23",/' node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/package.json
> pushd node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/
> npm install
> popd

**Comment by dermotos** [comment]
This workaround didn't work for me. I've replaced node-xmpp-client in the harmonyhubjs-client package to the 1.0.0-alpha23 release, but still receive the same `response` undefined error

Edit: Ok, got it working by making the edit manually. Thanks.

**Comment by JawsomeJason** [comment]
@dermotos what exactly do I need to edit manually?

**Comment by AppleTechy** [comment]
Hello. I seem to have the same problem. After I installed the solution above it seems to be working. Do you have an ETA when it will be fully fixed in the main package? Thanks @sushilks

**Comment by AppleTechy** [comment]
@thejase Just run the command given `sed -i.bak 's/"node-xmpp-client".*/"node-xmpp-client":"1.0.0-alpha23",/' node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/package.json
pushd node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/
npm install
popd` and that worked for me

**Comment by sushilks** [comment]
This problem has been solved in the latest version of "harmonyhubjs-client", 
If you re-build the project it will automatically pick up the latest version, I did the bump in the "sushilks/harmonyHubUtil" project for picking it up. 

Will close the issue soon if no more problems are reported

**Comment by sushilks** [comment]
not seen again.
