### ISSUE TITLE
Faster connection/execution possible?

### ISSUE THREAD

**Issue by badrabbit** [sushilks/harmonyHubCLI#10]
Is there a way to speed the connection to the hub up?
Right now a single Volume Up command needs up to 2 seconds before being executed.

Maybe keep the connection always open?

**Comment by sushilks** [comment]
There can be an option to have the connection always open, it will be require another mechanism to allow a running process to receive command. 
I will not have time to work on this feature, Would love to get a pull request on this if you or anyone else wants to add it.

**Comment by wgscott** [comment]
What if the volume command was modified to accept as an argument an integer from 1 to 100 to enable setting volume to a specific level?

**Comment by sushilks** [comment]
yes that should possible, feel free to send a pull request for it.
