### ISSUE TITLE
For some devices multiple commands are executed too fast?

### ISSUE THREAD

**Issue by odelma** [sushilks/harmonyHubCLI#11]
Hi,

This has been a  great addition for my Domoticz installation, thanks a lot! The only thing where I've been struggling a little bit is when I try to send multiple commands to my receiver (e.g. volume up five levels) it sometimes misses and sometimes even interprets one command as two and I suspect this is because it cannot keep up with the phase the commands are coming in. It would be great if you would consider adding an additional switch that would allow a delay to be set (e.g. in milliseconds) between sending multiple commands. 

edit: just found this https://github.com/sushilks/harmonyHubCLI/issues/4#issuecomment-185529207 I think it will solve the problem for me, no need to be able to set different delays at this point...😄

**Comment by sushilks** [comment]
Great if you are able to use the patch on #4 
Let me know if the problem is not solved.

**Comment by odelma** [comment]
Yes, it seems that 250ms is something my receiver can keep up with, 200ms still caused all sorts of problems... :smile:

For reference (in case someone struggles with similar issues), the receiver is quite old Sony STR-DG820.
