### ISSUE TITLE
Possible to set delays?

### ISSUE THREAD

**Issue by entmike** [sushilks/harmonyHubCLI#12]
Is it possible to set a delay between commands?

For instance I have this statement:

`node /usr/lib/node_modules/harmonyHubCLI/harmonyHubCli.js -l 192.168.1.20 -d 'Xfinity DVR' -c '["8","0","3","OK"]' -m`

It seems my DVR needs some wait-time between entering channel 803 and pressing OK, so it's not picking up the OK entry.

PS - Thanks for making this utility, I love it!  It makes my Harmony Hub actually do what I want it to!

**Comment by sushilks** [comment]
Give this a try to see if it works. 
https://github.com/sushilks/harmonyHubCLI/issues/4#issuecomment-185529207

**Comment by entmike** [comment]
Thanks for the heads up, but I went ahead and just wrapped it all in a bash script for convenience.  It turns out that just issuing two separate CLI commands was enough of a delay, otherwise I could have just done a sleep command.  I'll leave the below script for reference in case someone has the same issue:


`#!/bin/bash

channel=$1
hub=$2
commands=[

if [ "$channel" == "NBC" ]; then channel=805; fi
if [ "$channel" == "ABC" ]; then channel=803; fi
if [ "$channel" == "CNN" ]; then channel=849; fi
if [ "$channel" == "AMC" ]; then channel=825; fi

for (( i=0; i<${#channel}; i++ )); do
  digit="${channel:$i:1}"
  commands=$commands$sep\"$digit\"
  sep=,
done
commands=$commands]
echo $commands
echo "Switching to channel $channel"
node /usr/lib/node_modules/harmonyHubCLI/harmonyHubCli.js -l "$hub" -d 'Xfinity DVR' -c "$commands" -m
node /usr/lib/node_modules/harmonyHubCLI/harmonyHubCli.js -l "$hub" -d 'Xfinity DVR' -c 'OK'
`

**Comment by sushilks** [comment]
Great, If you want you can commit the bash script into the repo as pull request.
