### ISSUE TITLE
cannot read commands for some devices on brand new harmony elite hub

### ISSUE THREAD

**Issue by stbuerger** [sushilks/harmonyHubCLI#17]
### cannot read commands for some devices on brand new harmony elite hub

```
sb@SBULX90:~/SRC/harmonyHubCLI# nodejs harmonyHubCli.js -l 192.168.1.xyz -r devices
Connecting to hub at 192.168.1.xyz
List of devices programmed on the Hub
        0. 'Samsung-Fernseher'
        1. 'Amazon Fire TV'
        2. 'Telekom-DVR'
```

THEN .. with "Amazon Fire TV" ..
```
sb@SBULX90:~/SRC/harmonyHubCLI# nodejs harmonyHubCli.js -l 192.168.1.xyz -d "Amazon Fire TV" -r commands
Connecting to hub at 192.168.1.xyz
List of commands supported by device:Amazon Fire TV
        0. 'DirectionDown'
        1. 'DirectionLeft'
        2. 'DirectionRight'
        3. 'DirectionUp'
        4. 'OK'
        5. 'Stop'
        6. 'Play'
        7. 'Rewind'
        8. 'Pause'
        9. 'FastForward'
        10. 'SkipBack'
        11. 'SkipForward'
        12. 'Menu'
        13. 'Back'
        14. 'Sleep'
        15. 'Exit'
        16. 'Delete'
        17. 'Home'
```
WORKS ! BUT with 'Samsung-Fernseher' or 'Telekom-DVR' it returns with neither result nor errror ..
```
sb@SBULX90:~/SRC/harmonyHubCLI# nodejs harmonyHubCli.js -l 192.168.1.xyz -d 'Samsung Fernseher' -r commands
Connecting to hub at 192.168.1.xyz
sb@SBULX90:~/SRC/harmonyHubCLI#
```

any idea/hint

thx
-sb

**Comment by sushilks** [comment]
I don't have "harmony elite hub" so can't say what is broken, likely this will require some debug on the harmonyHubUtil to see what is broke.

**Comment by giejay** [comment]
I have the same issue, with the regular hub and activities: 

node /node_modules/harmonyHubCLI/harmonyHubCli.js -l 192.168.2.xyz -a "Tv Kijken" -r commands
Connecting to hub at 192.168.2.20

And then it hangs... 

Sending a command on a device works: 
node /node_modules/harmonyHubCLI/harmonyHubCli.js -l 192.168.2.20 -d "LG TV" -r commands
Connecting to hub at 192.168.2.20
List of commands supported by device:LG TV
	0. 'PowerOff'
	1. 'PowerOn'
	2. 'PowerToggle'
	3. '.'
	4. '-'

**Comment by sushilks** [comment]
I verified with the latest packages and head that it works on my side. 
Looks like some debug will be required to find the problem you are having.

**Comment by dlastov** [comment]
stbuerger: May the issue be related to the '-' character in the name of the devices? The devices can be renamed, so you can try to replace the character with a space.

giejay: I think that the '-r command' does not make sense in the combination with an activity, just with the devices. Yet, ideally the script shouldn't hang but output an error in such situation.
