### ISSUE TITLE
Ceased to work with firmware 4.15.206

### ISSUE THREAD

**Issue by dlastov** [sushilks/harmonyHubCLI#18]
Until recently I has using harmonyHubCLI with 2 Harmony Hubs, with firmware 4.15.201.

After an upgrade to the current firmware 4.15.206 I am getting following error on each of the hubs:

```
$ node /opt/harmonyHubCLI/harmonyHubCli.js -l 192.168.0.104
Connecting to hub at 192.168.0.104
errorhub { Error: connect ECONNREFUSED 192.168.0.104:5222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.0.104',
  port: 5222 }
```

The hubs continue to work fine with the Harmony application for Android.

**Comment by sushilks** [comment]
Could it be due to this
https://www.home-assistant.io/blog/2018/12/17/logitech-harmony-removes-local-api/

Looks like with new firmware they disabled the API for control.

**Comment by dlastov** [comment]
Thanks for the link. I tried the firmware downgrade but no luck for me (the desktop app did not recognize connected hub during more than 20 minutes).
Apparently Logitech does not intend to return the API.

**Comment by whirka** [comment]
There is a beta firmware update that should now fix this.
https://community.logitech.com/s/question/0D55A00008D4bZ4/harmony-hub-firmware-update-fixes-vulnerabilities?s1oid=00Di0000000j2Ck

**Comment by dlastov** [comment]
I confirm that the beta firmware (4.15.210) works, I was able to update to it and use the harmonyHubCLI again!

**Comment by nikagl** [comment]
Thanks for this, let's hope they come with a good solution to still control our devices (securely) with XMPP in the final firmware too (I would expect/hope for a whitelist of IP's to continue to use it the way we did)...

**Comment by xraken** [comment]
I did the firmware update to 4.15.210 but it is still not connecting (this was working fine before the firmware disabled xmpp support). Here's what I get:
```
[ubuntu-16.04]$ node harmonyHubCli.js
Starting hub Discovery
  Hub Found at :192.168.2.163
Connecting to hub at 192.168.2.163
```

and it hangs forever. Is there anything else I need to do?

**Comment by xraken** [comment]
> I did the firmware update to 4.15.210 but it is still not connecting (this was working fine before the firmware disabled xmpp support). Here's what I get:
> 
> ```
> [ubuntu-16.04]$ node harmonyHubCli.js
> Starting hub Discovery
>   Hub Found at :192.168.2.163
> Connecting to hub at 192.168.2.163
> ```
> and it hangs forever. Is there anything else I need to do?

Turned out if I used any specific query or command it works fine, for some reason the "node harmonyHubCli.js" makes it look like it is hanging.

**Comment by dlastov** [comment]
I think that this issue can be closed:
https://community.logitech.com/s/question/0D55A00008OsX3CSAV/update-to-accessing-harmony-hubs-local-api-via-xmpp
After the last automatic upgrade from the development firmware harmonyHubCLI actually stopped working. I had to go to the Harmony app: Harmony Setup/Add Edit Devices/Hub and disable and than enable again the XMPP and it is ok now.
