### ISSUE TITLE
Can't install on El Capitan?

### ISSUE THREAD

**Issue by jcvignes** [sushilks/harmonyHubCLI#2]
Unfortunately, I have tried to install it on my El Capitan Mac Mini and it generates an error of which I can’t make sense… Do you think you could help me? 

I’ve downloaded the Git and the latest js.node on my Mac. 

Many thanks,
JC

Home-Office-de-JC-Vignes:harmonyHubCLI-master jcvignes$ npm install

node-stringprep@0.6.2 install /Users/jcvignes/Downloads/harmonyHubCLI-master/node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/node_modules/node-stringprep
node-gyp rebuild

 SOLINK_MODULE(target) Release/node_stringprep.node

node-stringprep@0.7.2 install /Users/jcvignes/Downloads/harmonyHubCLI-master/node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
node-gyp rebuild

 SOLINK_MODULE(target) Release/node_stringprep.node

node-stringprep@0.7.2 install /Users/jcvignes/Downloads/harmonyHubCLI-master/node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/node-stringprep
node-gyp rebuild

 SOLINK_MODULE(target) Release/node_stringprep.node

iconv@2.1.11 install /Users/jcvignes/Downloads/harmonyHubCLI-master/node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
node-gyp rebuild

 CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
 LIBTOOL-STATIC Release/iconv.a
libtool: unrecognized option `-static'
libtool: Try`libtool --help' for more information.
make: **\* [Release/iconv.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jcvignes/Downloads/harmonyHubCLI-master/node_modules/harmony-hub-util/node_modules/harmonyhubjs-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.11 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jcvignes/Downloads/harmonyHubCLI-master/npm-debug.log

**Comment by sushilks** [comment]
I think this is a problem with the nodejs install on your mac, You can try debug this by running 'npm install node-gyp'
I think it's likely because node packages require some dev tools to be installed (xcode).
Please follow instructions on the web to get nodejs installed (a quick google gave me http://blog.teamtreehouse.com/install-node-js-npm-mac)
You can test if the install went ok if the 'npm install node-gyp ' works.

**Comment by sushilks** [comment]
I will close this issue as it's unrelated the cli.
