### ISSUE TITLE
Is there a way to execute group of actions?

### ISSUE THREAD

**Issue by johnsturgeon** [sushilks/harmonyHubCLI#3]
I added a group of commands to one of my activities, but it does not show up in the list of discovered commands.  I tried executing them sequentially using harmonyCLI, but unfortunately the sequence of actions needs to be a bit faster and it didn't work.

It would be nice if I could add multiple commands to one request.  Thoughts?

**Comment by sushilks** [comment]
With the latest version I have added an option to execute multiple command, 
have a look at readme for details.

**Comment by sushilks** [comment]
#4 Related.

**Comment by sushilks** [comment]
Closing this, will track with issue #4
