### ISSUE TITLE
Command Clarification

### ISSUE THREAD

**Issue by AppleTechy** [sushilks/harmonyHubCLI#4]
If I wanted it to change the channel to 1015 what  would my command look like? I have tried node harmonyHubCLI.js -d 'TiVo Roamio Pro' -c '1' '0' '1' '5' But that only renders be an invalid error. So I try node harmonyHubCLI.js -d 'TiVo Roamio Pro' -c '1''0''1''5' and node harmonyHubCLI.js -d 'TiVo Roamio Pro' -c '1015' which both don't give me an error but never get past the connecting to hub stage. Thanks for any help or advice! I have tried several other programs but non seem to be able to do the above correctly.

**Comment by sushilks** [comment]
With the latest version I have added an option to execute multiple command, 
have a look at readme for details. 

Try:
node harmonyHubCLI.js  -d 'TiVo Roamio Pro'   -c '["1","0", "1", "5"]' -m

**Comment by AppleTechy** [comment]
@sushilks Thanks for the help. Whenever I use the command I get a succesful send message on my computer. `node harmonyHubCLI.js -l 192.xxx.x.xx -d 'TiVo Roamio Pro' -c '["1","0", "1", "5"]' -m
Connecting to hub at 192.xxx.x.xx
execute command received 
Triggering On device TiVo Roamio Pro command 1
Triggering On device TiVo Roamio Pro command 0
Triggering On device TiVo Roamio Pro command 1
Triggering On device TiVo Roamio Pro command 5
Command '["1","0", "1", "5"]' for device 'TiVo Roamio Pro' executed successfully.
`
But for some reason my TiVo only receives a partial command. The closest I have gotten it to do is channel 101. It seems to receive the 101 instantaneously and then set there waiting for the input of the last number. Or I have had it only go to channel 10. I have even had it only recieve the channel 0 but that was most likely user error as I was getting tired of guess and check so I issued the command repeatedly in a row to see if that did anything that benefit me. Is your software set for a delay in between commands? If not do you think this is an issue with my Hub or simply a malfunction on the networking side of my computer?

**Comment by sushilks** [comment]
That's strange, when I did the testing on my tivo it worked like a charm. 
To add delay you will need to modify the code in https://github.com/sushilks/harmonyHubUtil
you can find the file in "node_modules/harmony-hub-util/harmonyHubUtils.js"
the function that is run is at line number 68-90

Here is a patch for 200 ms delay between commands

```
diff --git a/harmonyHubUtils.js b/harmonyHubUtils.js
index b42a12a..d9981e8 100644
--- a/harmonyHubUtils.js
+++ b/harmonyHubUtils.js
@@ -80,7 +80,9 @@ function executeDeviceCommandListDF(deferred, dev, device, commandList) {
                     if (commandList.length == 0) {
                         deferred.resolve(true);
                     } else {
-                        self._executeDeviceCommandListDF(deferred, dev, device, commandList);
+                        setTimeout(function() {
+                           self._executeDeviceCommandListDF(deferred, dev, device, commandList);
+                        }, 200);
                     }
                 });
                 return;
```

**Comment by AppleTechy** [comment]
@sushilks Thanks for the response. Little confused on what I was suppose to patch the util.js For me on line 68-90 it currently is what is below. Am I supposed to replace the entire thing with the patch you have above? Or am I suppose to insert it? The plus and minus signs are throwing me off. Thanks for the advice.

> function executeDeviceCommandListDF(deferred, dev, device, commandList) {
    var self = this;
    var command = commandList.shift();
    dev.controlGroup.filter(function (group) {
        group['function'].filter(function (action) {
            var encodedAction, dt;
            if (JSON.parse(action.action).command === command) {
                console.log("Triggering On device " + device + " command " + command);
                encodedAction = action.action.replace(/\:/g, '::');
                dt = 'action=' + encodedAction + ':status=press';
                //console.log("Sending Action = " + dt);
                self._harmonyClient.send('holdAction', dt).then(function () {
                    if (commandList.length == 0) {
                        deferred.resolve(true);
                    } else {
                        self._executeDeviceCommandListDF(deferred, dev, device, commandList);
                    }
                });
                return;
            }
        });
    });
}

**Comment by AppleTechy** [comment]
@sushilks With the delay I got it to work successfully once. After that I couldn't get it to work again. When I was testing it an idea hit me, TiVo automatically prompts you to go to the HD channel if it exists. You have to physically change to the channel. Do you own a TiVo? If so do you know what I am talking about? I figured the least amount of commands has the best chance to work. So I figured why not try the commands below. But when I try that it tells me "D" isn't a valid command. Any ideas? 

> node harmonyHubCLI.js -l 192.168.1.155 -d 'TiVo Roamio Pro' -c ‘[“6”,”1”, “D”]’ -m

**Comment by sushilks** [comment]
I have a very old TIVO which does not show the behaviour you mentioned. 
If I had to guess I would think you will need a bit longer delay between the ["6", "1" ] and ["D"] , i.e. send "6" wait(200ms) send "1" wait(1sec) send "D".
The timing will need to be adjusted, in general this type of timing based architecture/design is not a very good idea. From time to time it will fail to do the desired task. For now I don't have any better suggestion.

**Comment by AppleTechy** [comment]
When I said it won't recognize the "D" it wasn't the TiVo but rather the
CLI program that built said it was an invalid command. Not sure if that was
based off a response it got from the TiVo or a response from the
application running on my computer.

**Comment by sushilks** [comment]
Ah!, You can use the CLI to dump the full list of command supported by your device. 
I think it's the "-r" option with the device specified. It's possible that "D" is called something else in the command list.

**Comment by sushilks** [comment]
@AppleTechy any updates ?

**Comment by AppleTechy** [comment]
Sorry for no updates1 I had taken a break because it had gotten to a point
were I wanted to through my computer and harmony hub out the window. I will
try again this weekend, I also got a new router so I will see if that
somehow changed anything.

**Comment by AppleTechy** [comment]
@sushilks It seems my previous command issues came from bad software being on my hub. Not necessarily an issue with your application. I updated my hub software and it seems to actually send and receive all the commands correctly from the computer now. Have to do a little bit more testing and I will close the issue. :) I ended up getting it to work with just sending numbers to get to the HD channels and not bothering with pressing "D".

**Comment by sushilks** [comment]
Looks like this was resolved.

**Comment by github22222** [comment]
I was struggling with the issue of multiple commands not working. The key was appreciating that under Windows command line quotes need to be used not single quotes. For example, the device needs to be "TiVo DVR" not 'TiVo DVR' . The multiple command needs to be like this, for example, -d "TiVo DVR" -c "[""1"",""1"",""1"",""1""]" -m. Apparently the single quote needs to be escaped like in CSV data.
