### ISSUE TITLE
Multi Command sends the last command twice

### ISSUE THREAD

**Issue by johnsturgeon** [sushilks/harmonyHubCLI#5]
I've played around with multi commands and from what I can tell, it sends the last command twice.

**Comment by sushilks** [comment]
Not sure what you are seeing, I did some basic testing in my deployment and
did not see any problem like this.
Please provide some more details.

**Comment by johnsturgeon** [comment]
I have a Receiver that I need to boost the center volume, I run the following command:
`node harmonyHubCli.js -l 192.168.0.103 -d 'AV Receiver' -c '["Audio", "DirectionUp","DirectionUp","DirectionRight","DirectionRight"]' -m`
but the DirectionRight gets sent three times.  The _output_ on shows only two, but three are sent.  I fix it by changing the command to:
`node harmonyHubCli.js -l 192.168.0.103 -d 'AV Receiver' -c '["Audio", "DirectionUp","DirectionUp","DirectionRight","DirectionRight","0"]' -m`
Where the '0' is pretty much ignored by my receiver.

Note, this could just be a problem with the harmony system..  I'm not really sure

**Comment by sushilks** [comment]
@johnofcamas Any updated on this ?

**Comment by johnsturgeon** [comment]
Nope.  I haven't had time to figure out what the problem might be, but suffice it to say, it's probably a problem with Harmony and not the CLI app.  I recommend closing this

**Comment by sushilks** [comment]
Ok closing it for now, feel free to ping back.
