### ISSUE TITLE
Issues controlling Fire TV

### ISSUE THREAD

**Issue by destructure00** [sushilks/harmonyHubCLI#7]
Commands sent to Fire TV through HarmonyHubCLI work intermittently. My setup is correct and I do not have any issues consistently controlling infrared devices through CLI. Fire TV commands (I'm just working on Play and Pause at the moment) work intermittently, maybe one out of every 10 times. If I use the actual Harmony remote or app on my phone, the success rate for the first command sent through CLI afterward seems to be higher. I have tried controlling through the Fire TV activity with -a 'Watch Fire TV' -c 'TransportBasic,Pause' as well as through the device with -d 'Amazon Fire TV' -c 'Pause' with the same result either way. 

Is this because Fire TV is controlled through the Bluetooth connection rather than an infrared signal? Has anyone found a resolution to this?

**Comment by destructure00** [comment]
The issue seems to be that when triggering a button through the CLI, Fire TV thinks the button is being held down. I spoke with someone else who's experience confirms this, he has a different app for controlling the Harmony hub through SmartThings and said he has to follow a button command with a "release" command. How would I do this through CLI?

**Comment by destructure00** [comment]
Am I correct that this is where the Activity commands are generated and sent to the hub? How can this be modified to send a release command after the press? This is from HarmonyHubUtils.js. 

function executeActivityCommandListDF(deferred, act, activity, commandList) {
    var self = this,
        command = commandList.shift(),
        cmd = command.split(',');
    act.controlGroup.filter(function (cg) {
            if (cg.name === cmd[0]) {
                cg.function.filter(function (fn) {
                    var dt, encodedAction;
                    if (fn.label === cmd[1]) {
                        console.log("Triggering On Activity " + activity + " command " + command);
                        encodedAction = fn.action.replace(/:/g, '::');
                        **dt = 'action=' + encodedAction + ':status=press';**
                        //console.log("\tSending Action = " + dt);
                        self._harmonyClient.send('holdAction', dt).then(function () {
                            if (commandList.length == 0) {
                                deferred.resolve(true);
                            } else {
                                return self._executeActivityCommandListDF(deferred, act, activity, commandList);
                            }
                        });
                        return;
                    }
                });
            }
    });
}

**Comment by sushilks** [comment]
I am not sure, if you want to dig into what types of commands are supported by underlying library you will need to look at "https://github.com/swissmanu/harmonyhubjs-client"
If the remote has explicit commands that it shows as release command you can execute two commands back to back using the method discussed in https://github.com/sushilks/harmonyHubCLI/issues/4

You can also trying executing another NOP command (Something that has no effect) right after the first command and see if that resolves the problem.

Let us know how it goes .

**Comment by destructure00** [comment]
I think if I could add a line for **dt = 'action=' + encodedAction + ':status=release';** after the press command in the code I pasted above it might work. I just am not familiar enough with javascript to know the proper syntax. I played around with it some last night and could not get it to work correctly.

**Comment by destructure00** [comment]
Here is what I had in mind, I am not home so I can't test but hopefully this gives an idea of what I'm trying to do.

function executeDeviceCommandListDF(deferred, dev, device, commandList) {
    var self = this;
    var command = commandList.shift();
    dev.controlGroup.filter(function (group) {
        group['function'].filter(function (action) {
            var encodedAction, dt;
            if (JSON.parse(action.action).command === command) {
                console.log("Triggering On device " + device + " command " + command);
                encodedAction = action.action.replace(/:/g, '::');
                **dt = 'action=' + encodedAction + ':status=press';**
                //console.log("Sending Action = " + dt);
                **self._harmonyClient.send('holdAction', dt);**
                **dt = 'action=' + encodedAction + ':status=release';**  
                **self._harmonyClient.send('holdAction', dt).then(function () {**
                    if (commandList.length == 0) {
                        deferred.resolve(true);
                    } else {
                        self._executeDeviceCommandListDF(deferred, dev, device, commandList);
                    }
                });
                return;
            }
        });
    });
}

**Comment by sushilks** [comment]
You have to check if "status=release" is supported by the downstream
library that is being used,
The code will be slightly different, requires a bit of javascript
knowledge. ( I will see if this weekend I can spend some time but have a
busy schedule).

**Comment by destructure00** [comment]
That would be great if you can, thanks. 

I've been digging around in this repository
https://github.com/joejarvis64/j64.Harmony

and he uses both press and release commands, so I think Harmony Hub will accept the release. His code is quite a bit different of course but he has functions like 
myHub.SendCommand(j64Config.ChannelDevice, command, "press")
and
myHub.SendCommand(action.Device, action.Function, "release")

**Comment by destructure00** [comment]
I can confirm that the release command works. I manually commanded the release by first running a Pause command using your original code, then modifying the dt variable to 
**dt = 'action=' + encodedAction + ':status=release';**
then running the Pause again, then changing back to ':status=press', running a play command, changing back to release, etc etc. This gives repeatable successful commands. I think it just needs to be added to the code so that the press and subsequent release happen as part of the same command function.

**Comment by destructure00** [comment]
Got it. This works, for a single command anyway. I have not tried multiple. 

function executeDeviceCommandListDF(deferred, dev, device, commandList) {
    var self = this;
    var command = commandList.shift();
    dev.controlGroup.filter(function (group) {
        group['function'].filter(function (action) {
            var encodedAction, dt;
            if (JSON.parse(action.action).command === command) {
                console.log("Triggering On device " + device + " command " + command);
                encodedAction = action.action.replace(/:/g, '::');
                dt = 'action=' + encodedAction + ':status=press';
                console.log("Sending Action = " + dt);
                self._harmonyClient.send('holdAction', dt).then(function () {
                    if (commandList.length == 0) {
                        deferred.resolve(true);
                    } else {
                        self._executeDeviceCommandListDF(deferred, dev, device, commandList);
                    }
                });
                dt = 'action=' + encodedAction + ':status=release';
                console.log("Sending Action = " + dt);
                self._harmonyClient.send('holdAction', dt).then(function () {
                    if (commandList.length == 0) {
                        deferred.resolve(true);
                    } else {
                        self._executeDeviceCommandListDF(deferred, dev, device, commandList);
                    }
                });
                return;
            }
        });
    });
}

**Comment by sushilks** [comment]
@destructure00 
I have updated the utility to do a release after every press command, 
Here is the patch set https://github.com/sushilks/harmonyHubUtil/pull/2

If you can do an "npm update" to get the 1.2.0 version of "harmony-hub-util" and test with fire-tv.
Post back your findings.

**Comment by destructure00** [comment]
I updated and it seems to be working correctly. Thank you!

**Comment by sushilks** [comment]
Thanks for testing it out @destructure00
