### ISSUE TITLE
What activity is active?

### ISSUE THREAD

**Issue by trp88** [sushilks/harmonyHubCLI#9]
Hello, firstly, let me start by saying that I love this little CLI and this is not really an issue, more a question.

Is there any way to expose what activity is currently active using this, or some other method?

**Comment by trp88** [comment]
Ah, a bit more playing about and I found it:

harmonyhub-cli -l <Harmony IP> -r status

Throw that in the FAQ for other n00bs like me.

**Comment by sushilks** [comment]
Thanks, of you don't mind can you do a pull request with this change?
